### PR TITLE
fix database migration

### PR DESCRIPTION
**Pull request by joschahenningsen**
@SiKreuz noticed, that the current version of the app can be installed but occasionally crashes on upgrade due to the database changes I introduced. 

@SiKreuz, can you verify that this fixes the exact problems you had?

### CODE REVIEW

**Review by SiKreuz — APPROVED** [review]
Thank you Joscha. I can confirm, that this changes fix the upgrade. My build is not crashing anymore.

**Review by kordianbruck — APPROVED** [review]

**Comment by kordianbruck** [comment]
Do you need to update the database json file?

**Comment by joschahenningsen** [comment]
No, that only changes when the schema is updated (everything that is annotated with Entity for example) the migration doesn't affect it.

**Comment by kordianbruck** [comment]
You know this stuff better by now probably than me :+1:

**Pull request merged**
