### PR TITLE
Issue/1416 migrate tumui to viewbinding

### PR DESCRIPTION
**Pull request by Liqs-v2**
## Issue

This fixes the following issue(s): Second part for fixing #1416 

## Why this is useful for all students
Having a working app that can easily be maintained and expanded upon using the newest android features will improve the experience for users and developers alike.

### component.tumui
- [x] `calendar`
- [x] `feedback`
- [x] `grades`
- [x] `lectures`
- [x] `person`
- [x] `roomfinder`
- [x] `tuitionfees`

### CODE REVIEW

**Comment by Liqs-v2** [comment]
There currently is some duplication of code with #1417 in here, in order to be able to work on the **tumui migration in a seperate branch/PR**. Once #1417 is merged this will be fixed.

**Comment by Liqs-v2** [comment]
This would also be done, apart from the aforementioned code duplication @joschahenningsen

**Comment by joschahenningsen** [comment]
Feel free to create branches on this repo in the future instead of your fork, you should have write access if I recall correctly :)

**Comment by joschahenningsen** [comment]
Also, could you merge master into your branch so the duplication from the other pr is not in here?

**Comment by Liqs-v2** [comment]
> Feel free to create branches on this repo in the future instead of your fork, you should have write access if I recall correctly :)

I ll check in with the coordinators of my lab for this and check in on whether thats fine with them.

**Comment by Liqs-v2** [comment]
> Also, could you merge master into your branch so the duplication from the other pr is not in here?

Duplicate code is now removed. Can also review/merge this now.

**Comment by Liqs-v2** [comment]
Just a reminder that this should be ready to merge @joschahenningsen @kordianbruck

**Comment by joschahenningsen** [comment]
> Just a reminder that this should be ready to merge @joschahenningsen @kordianbruck 

Thanks for the bump, forgot about this :)

**Review by joschahenningsen — APPROVED** [review]

**Pull request merged**
