### PR TITLE
Fixes existing tests crashing

### PR DESCRIPTION
**Pull request by Liqs-v2**
## Issue

This fixes the following issue(s): Currently all of the tests that exist and are not ignored crash with the same error [see my comment on another issue.](https://github.com/TUM-Dev/Campus-Android/issues/1378#issuecomment-950571857). This means that even the code for which tests exist, can not be verified.

### Current
Failing_tests_tca

### Fixed
FirebaseApp_initialized

## Implementation
**FirebaseApp, which is normally initialized by FirebaseInitProvider *before Application.onCreate()* is not run in the test source set**. Thus, FirebaseApp needs to manually be initialized, to that ensure FirebaseCrashlytics works.

## Why this is useful for all students
Ensuring that the test suite is up and running prevents introducing new errors, makes it easier to work on TCA and increases usability for users.

### CODE REVIEW

**Comment by Liqs-v2** [comment]
@joschahenningsen Should I upgrade to gradle 7.x or why is the build failing here?

**Comment by Liqs-v2** [comment]
Okay so currently I cannot run the app anymore at all. **This is on the master branch, before any of my commits/merges.**

```
2021-11-19 13:36:15.228 18599-18599/de.tum.in.tumcampus E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.tum.in.tumcampus, PID: 18599
    java.lang.ExceptionInInitializerError
        at leakcanary.internal.InternalLeakCanary.addDynamicShortcut(InternalLeakCanary.kt:287)
        at leakcanary.internal.InternalLeakCanary.invoke(InternalLeakCanary.kt:149)
        at leakcanary.internal.InternalLeakCanary.invoke(InternalLeakCanary.kt:40)
        at leakcanary.internal.InternalAppWatcher.install(InternalAppWatcher.kt:71)
        at leakcanary.AppWatcher.manualInstall(AppWatcher.kt:206)
        at leakcanary.internal.AppWatcherInstaller.onCreate(AppWatcherInstaller.kt:29)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: shark.AndroidReferenceMatchers.values []
        at java.lang.Enum.enumValues(Enum.java:270)
        at java.lang.Enum.access$000(Enum.java:61)
        at java.lang.Enum$1.create(Enum.java:277)
        at java.lang.Enum$1.create(Enum.java:275)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
        at java.util.EnumSet.getUniverse(EnumSet.java:407)
        at java.util.EnumSet.noneOf(EnumSet.java:109)
        at java.util.EnumSet.allOf(EnumSet.java:130)
        at shark.AndroidReferenceMatchers$Companion.getAppDefaults(AndroidReferenceMatchers.kt:1259)
        at leakcanary.LeakCanary$Config.<init>(LeakCanary.kt:82)
        at leakcanary.LeakCanary.<clinit>(LeakCanary.kt:292)
        at leakcanary.internal.InternalLeakCanary.addDynamicShortcut(InternalLeakCanary.kt:287) 
        at leakcanary.internal.InternalLeakCanary.invoke(InternalLeakCanary.kt:149) 
        at leakcanary.internal.InternalLeakCanary.invoke(InternalLeakCanary.kt:40) 
        at leakcanary.internal.InternalAppWatcher.install(InternalAppWatcher.kt:71) 
        at leakcanary.AppWatcher.manualInstall(AppWatcher.kt:206) 
        at leakcanary.internal.AppWatcherInstaller.onCreate(AppWatcherInstaller.kt:29) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.NoSuchMethodException: shark.AndroidReferenceMatchers.values []
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at java.lang.Enum.enumValues(Enum.java:267)
```

I **have tried removing** the **leak canary dependency** and **upgrading** it. Neither of which worked. This happens both when run normally or in debug mode.

**Comment by kordianbruck** [comment]
I'm not surprised, upgrading the Gradle version is a lot of work. I wouldn't advise working on it right now.

**Comment by kordianbruck** [comment]
I've fixed the tests on master branch. You had the right idea, but there was a simpler fix :>

**Pull request closed without merging**
