### PR TITLE
Add centralized search

### PR DESCRIPTION
**Pull request by thellmund**
## Issue

This fixes the following issue(s): #678 

## Screenshot
| Navigation drawer  | Search screen |
| ------------- | ------------- |
| Screenshot_1566729266 | Screenshot_1566729305 |

## Why this is useful for all students
- Single, easily accessible point for searching
- Avoid usage of ugly `SearchView` component

## Still to do
- [ ] List with recent search queries

Feedback welcome!

### CODE REVIEW

**Comment by kordianbruck** [comment]
omg - you are amazing Till! :heart:

**Comment by kordianbruck** [comment]
Any progress? :heart_decoration:

**Comment by thellmund** [comment]
Unfortunately no. If anyone wants to pick this up (and add a list of recent searches; optional), feel free to do so.

**Comment by PiotrKedra** [comment]
Hi, I tried to use this code but there are too many conflicts with the current master 😞. I created a new PR where I will implement it from the beginning, using some @thellmund ideas 😀

**Comment by CommanderStorm** [comment]
closed in favor of #1457

**Pull request closed without merging**
