### PR TITLE
Remove cast to ReviewException as result is unused

### PR DESCRIPTION
**Pull request by ctsk**
## Issue

This fixes the following issue(s):
- Resolves: #1531

## Why this is ~useful for all students~ an improvement

Could be inconsequential, could be that the bug is also encountered "in the wild". At the least it helps developers :)

### CODE REVIEW

**Comment by CommanderStorm** [comment]
@Liqs-v2 what was the intention with this?
Shouldn't this info be used instead show a modal?

**Comment by XSpielinbox** [comment]
As this bug also effects startup of the app for normal usage, e.g. on  Custom ROMs, I would be grateful, if this could be removed until there is new code that also works well on all devices.

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
What do you think about this change?

MainFragment.kt
````
} else {
    // There was some problem, log or handle the error code.
    Utils.showToast(requireContext(),R.string.in_app_review_failed_to_start)
    task.exception?.let { Utils.log(it) }
}
```

strings.xml
en: `<string name="in_app_review_failed_to_start">In App ReviewFlow failed to start</string>`
de: `<string name="in_app_review_failed_to_start">In App ReviewFlow konnte nicht gestartet werden</string>`

**Comment by CommanderStorm** [comment]
closed in favor of #1564

**Pull request closed without merging**
