### PR TITLE
Issue/1416 migrate to viewbindings

### LINKED ISSUE #1416: Migrate from kotlin synthetics to view binding
## Problem
Currently the project uses **kotlin synthetics** which have been **(deprecated)[https://developer.android.com/topic/libraries/view-binding/migration#groovy)** in favor of **view binding.**

## Suggested Enhancement :sparkles:
Migrate the codebase from kotlin synthetics to view binding, to make sure that the app does not completely break once kotlin synthetics are no longer supported.

This can potentially be done on a per module basis.

### PR DESCRIPTION
**Pull request by Liqs-v2**
## Issue

This fixes the following issue(s): First part for #1416 

## Why this is useful for all students
Having a working app that can easily be maintained and expanded upon using the newest android features will improve the experience for users and developers alike.

### component.ui
- [x] `overview`
- [x] `onboarding`
- [x] `openinghour`
- [x] `news`
- [x] `eduroam`
- [x] `chat`
- [x] `cafeteria`
- [x] `barrierfree`
- [x] `alarm`
- [x] `studyroom`
- [x] `ticket`
- [x] `transportation`
- [x] `tufilm`
- [x] `updatenote`

I will **open a new PR for the tumui component migration** to keep this already sizable PR managable.

### CODE REVIEW

**Comment by Liqs-v2** [comment]
What would the scope of a PR for migration ideally be for you? Per component package? So one for `overview` and another for `onboarding` for example?

This would lead to a flurry of PRs, but might be best to keep them small. Let me know what you think,

**Comment by Liqs-v2** [comment]
So the ui component is successfully migrated, I feel like adding the rest to this already large PR (in terms of files changed) would not be useful. Once this is merged I will open a new PR for component.tumui and one for the rest

**Comment by joschahenningsen** [comment]
Absolutely amazing!

**Comment by Liqs-v2** [comment]
Oh and this PR somehow also has commits that are already in master in it (see the first two commits in the PR). I tried, but couldnt quite figure out how to exclude them. If you know how, please let me know.

**Comment by Liqs-v2** [comment]
The **components that have cards attached** to them, would need a **bigger refactoring to make them compatible with view bindings**, as one would also need to change how the recycler view and thus cards are implemented. **For now I reverted them to use `findViewById`.**

**Comment by Liqs-v2** [comment]
Fixed this PR, so that the changes already in TUM-Dev:master aren't shown in here again. Please give this a review when you find time @joschahenningsen

**Comment by joschahenningsen** [comment]
Thanks for pinging me, I'll review both this evening 👌

**Review by joschahenningsen — APPROVED** [review]
This looks like a ton of work, thank you so much!

All changes make sense to me and are what I'd expect from the documentation. I'd still suggest another thorough testing session before the next release :D

**Pull request merged**
