### PR TITLE
Refactor settings in Kotlin

### PR DESCRIPTION
**Pull request by thellmund**
#1322 

This pull request converts the `UserPreferencesActivity` (now `SettingsActivity`) and `SettingsFragment` to Kotlin.

### CODE REVIEW

**Comment by kordianbruck** [comment]
So this also adds #646 KTX?

**Comment by thellmund** [comment]
It does. Now, whenever we‘re refactoring some part of the code where a ktx extension is available, we can use it.

**Comment by jacqueline8711** [comment]
@thellmund This is still behaving really weirdly and I don't know why. I get only a few icons about 50% of the time (waiting doesn't help). Some times the icon for one news source appears when I click on the check box and sometimes the checkbox doesn't respond to the click at all. When they don't respond and I go back to the main settings that page is blank. This happens both on my phone and the emulator

**Comment by thellmund** [comment]
Yes, it worked pretty reliable for me. I’ll try to take a look again and see if I noticed any issues.

**Comment by thellmund** [comment]
@jacqueline8711 I can’t reproduce your issues. Can you record a screencast and paste any suspicious console output heree?

**Comment by jacqueline8711** [comment]
Opened it a couple of times:
https://photos.app.goo.gl/augXxsxmA8Fjjf78A

**Pull request merged**
