### PR TITLE
Update token setup screenshots

### LINKED ISSUE #1379: Update Token Setup Screenshots
Since TUMonline 3.0 the interface has changed and users report "not being able to find the token management". I think it basically looks the same, but worth doing the effort and updating the screenshots.

### PR DESCRIPTION
**Pull request by joschahenningsen**
This fragment may need some attention (design-wise) but for now it should be fine to just swap the screenshots.

fixes #1379

### CODE REVIEW

**Review by kordianbruck — APPROVED** [review]

**Comment by FlorianDev** [comment]
would a localized version (en screenshots) make sense or is it self-explanatory?

**Comment by joschahenningsen** [comment]
Would make sense, I can do that later or tomorrow.

**Comment by joschahenningsen** [comment]
This looks much better as well because the new images fill the width of the screen now :+1: 
@kordianbruck is travis doing alright? The status doesn't change. Did we consider switching to gh-actions?

**Comment by kordianbruck** [comment]
Travis has been broken forever, but I never had the time to set this up on github actions.

**Review by kordianbruck — APPROVED** [review]

**Pull request merged**
