### PR TITLE
Replace anko

### PR DESCRIPTION
**Pull request by kunzef**
## Issue

This fixes the following issue(s):
- Resolves: #1573
- Improves how Asynchronous work is handled 

## Why this is useful for all students
Most likely users won't notice. But Anko has been archived since 2020 and thus not received improvements. Also the way how asynchronous work is done is not up to date / deprecated classes are used. This PR fixes this in all cases where previously Anko was used.

## How is Anko replaced
- for services through the corresponding native implementation
- for SharedPreferences through the androidx PreferenceManager
- asynchronous handling:
    - for impersistent work by binding to lifecycle using coroutines where possible
    - for persistent work by using WorkManager
- all other cases through native implementations see commit messages for every replacement

### CODE REVIEW

**Comment by kunzef** [comment]
Just discovered a bug where clicking `Recover Cards` on the main page crashes the app. I am currently investigating it and reverted the PR to a draft PR.

**Comment by kunzef** [comment]
> Just discovered a bug where clicking `Recover Cards` on the main page crashes the app. I am currently investigating it and reverted the PR to a draft PR.

This is fixed through #1594 

The PR should be working fine now. Regarding the merge-conflicts I can not resolve them on my side, unfortunately but I have attached fixes for QueryLocationsService (renamed to QueryLocationWorker) and for CacheManager. The conflicts in CalendarFragment are trivial. 

_QueryLocationWorker.kt_
```
class QueryLocationWorker(appContext: Context, workerParams: WorkerParameters) :
    Worker(appContext, workerParams) {

    private lateinit var locationManager: LocationManager

    override fun doWork(): Result {
        locationManager = LocationManager(applicationContext)

        Utils.log("Query location service worker started …")
        val calendarDao = TcaDb.getInstance(applicationContext).calendarDao()
        val roomLocationsDao = TcaDb.getInstance(applicationContext).roomLocationsDao()

        calendarDao.lecturesWithoutCoordinates
            .filter { it.location.isNotEmpty() }
            .mapNotNull { createRoomLocationsOrNull(it) }
            .also { roomLocationsDao.insert(*it.toTypedArray()) }

        // Do sync of google calendar if necessary
        val shouldSyncCalendar = Utils.getSettingBool(applicationContext, Const.SYNC_CALENDAR, false) &&
            ContextCompat.checkSelfPermission(applicationContext, Manifest.permission.WRITE_CALENDAR) == PackageManager.PERMISSION_GRANTED
        val syncManager = SyncManager(applicationContext)
        val needsSync = syncManager.needSync(Const.SYNC_CALENDAR, TIME_TO_SYNC_CALENDAR)

        if (shouldSyncCalendar.not() || needsSync.not()) {
            return Result.failure()
        }

        try {
            CalendarController.syncCalendar(applicationContext)
            syncManager.replaceIntoDb(Const.SYNC_CALENDAR)
            return Result.success()
        } catch (e: SQLiteException) {
            Utils.log(e)
            return Result.failure()
        }
    }

    private fun createRoomLocationsOrNull(item: CalendarItem): RoomLocations? {
        val geo = locationManager.roomLocationStringToGeo(item.location)
        return geo?.let {
            RoomLocations(item.location, it)
        }
    }

    companion object {

        private const val TIME_TO_SYNC_CALENDAR = 604800 // 1 week

        @JvmStatic
        fun enqueueWork(context: Context) {
            Utils.log("Query locations work enqueued")
            WorkManager.getInstance(context).enqueue(OneTimeWorkRequest.from(QueryLocationWorker::class.java))
        }
    }
}
```

_ChacheManager.kt_
```
class CacheManager @Inject constructor(private val context: Context) {

    val cache: Cache
        get() = Cache(context.cacheDir, 10 * 1024 * 1024) // 10 MB

    fun fillCache() {
        class WorkWhenReceived(appContext: Context, workerParams: WorkerParameters) :
            Worker(appContext, workerParams) {
            override fun doWork(): Result {
                syncCalendar()
                return Result.success()
            }
        }
        // start expedited background work
        val request = OneTimeWorkRequestBuilder<WorkWhenReceived>()
            .setExpedited(OutOfQuotaPolicy.RUN_AS_NON_EXPEDITED_WORK_REQUEST)
            .build()
        WorkManager.getInstance(context)
            .enqueue(request)
    }

    private fun syncCalendar() {
        TUMOnlineClient
                .getInstance(context)
                .getCalendar(CacheControl.USE_CACHE)
                .enqueue(object : Callback<EventsResponse> {
                    override fun onResponse(call: Call<EventsResponse>, response: Response<EventsResponse>) {
                        val eventsResponse = response.body() ?: return
                        val events = eventsResponse.events ?: return
                        CalendarController(context).importCalendar(events)
                        loadRoomLocations()
                    }

                    override fun onFailure(call: Call<EventsResponse>, t: Throwable) {
                        Utils.log(t, "Error while loading calendar in CacheManager")
                    }
                })
    }

    private fun loadRoomLocations() {
        // enqueues OneTimeWorkRequest
        QueryLocationsService.enqueueWork(context)
    }

    @Synchronized
    fun clearCache() {
        cache.delete()
    }
}
```

**Comment by tobiasjungmann** [comment]
I've rebased your branch on the latest version of the master branch.  To make the comparison easier I've done it on a new [Branch](https://github.com/TUM-Dev/Campus-Android/compare/replace-anko-rebase-overview) Some lines in the same files concerning the card refactoring and the preference rework did overwrite themselves. Please have a look at it to make sure that the most recent changes of both are added and are working together since you probably have a much better overview about the changes than I have :D What I've seen from the code so far looks good and should be easy to merge afterwards!

**Comment by CommanderStorm** [comment]
@tobiasjungmann your rebase looks good to me. Can I merge it?

**Comment by CommanderStorm** [comment]
I rebased this in https://github.com/TUM-Dev/Campus-Android/pull/1615
⇒ Works without errors, merging as soon as the build succeeds

**Pull request closed without merging**
